### ISSUE TITLE
Python 3.12 issue

### ISSUE THREAD

**Issue by hhrhhr** [zackees/fastled-wasm#3]
Hello. 
When I use Python 3.12 environment, after installing fastled (`pip install fastled`), _docker-**2.7.0**_ package is installed, which requires _docker_pycreds-0.4.0_ package, which does not work in Python 3.12:
```
  File "D:\Users\hhr\pipx_msys\venvs\fastled\lib\python3.12\site-packages\dockerpycreds\utils.py", line 1, in <module>
    import distutils.spawn
ModuleNotFoundError: No module named 'distutils'
```
But if I use Python 3.11, it installs the _docker-**7.1.0**_ package, which is newer, doesn't require _docker_pycreds_, and has no issues with Python 3.12.

**Comment by hhrhhr** [comment]
I switched from msys2 and pipx to uv and when installing fastled all dependencies work without problems with Python 3.12.

**Comment by zackees** [comment]
Someone else is going to hit this bug. Good to know about this footgun. I'll add `distutils` package and update.

**Comment by zackees** [comment]
I think I know what happened: you had an old version of docker py SDK and I didn't pin a minimum version. I've gone ahead and added minimum versions for all dependencies. This should take care of it for you as it will force an update on that dep.
