### ISSUE TITLE
fastled-windows-x64 error

### ISSUE THREAD

**Issue by hhrhhr** [zackees/fastled-wasm#4]
With local docker or web compiler and fastled-windows-x64.exe v1.1.60 livereload tool do not run.

```
...
Web compilation successful
  Time: 17.88
  output: h:\devel\wasm_test3\fastled_js
  hash: 6815e856db258c4210bc2e2c8bab3c52171460914d73ded689aca218f94678a9
  zip size: 202415 bytes
Will compile on sketch changes or if you hit the space bar.
Press Ctrl+C to stop...
usage: fastled-windows-x64.exe [-h] [--version] [--init [INIT]] [--just-compile] [--web [WEB]] [-i]
                   [--profile] [--force-compile] [--no-auto-updates] [--update] [--localhost]
                   [--server] [--debug | --quick | --release]
                   [directory]
fastled-windows-x64.exe: error: unrecognized arguments: --multiprocessing-fork pipe_handle=996
usage: fastled-windows-x64.exe [-h] [--version] [--init [INIT]] [--just-compile] [--web [WEB]] [-i]
                   [--profile] [--force-compile] [--no-auto-updates] [--update] [--localhost]
                   [--server] [--debug | --quick | --release]
                   [directory]
fastled-windows-x64.exe: error: unrecognized arguments: --multiprocessing-fork pipe_handle=932
```

**Comment by zackees** [comment]
Thanks, it turns out it's a problem with the pyinstaller. I was able to reproduce the issue and fix it.

Btw, thanks for filing this bug before the official release. What do you think of the fastled compiler?

**Comment by hhrhhr** [comment]
I think fastled compiler hasn't quite kept up with the changes in FastLED.

v1.1.66, cd ...\fastled-wasm-main\examples\wasm && fastled --web:
When I click on any button nothing happens, in the browser console I see the following:
```
index.js:78 0.1s UI elements added, showing UI controls container
index.js:78 0.1s Creating Fast GraphicsManager with canvas ID myCanvas
ui_manager.js:118 Uncaught TypeError: Cannot read properties of undefined (reading 'setAttribute')
    at HTMLButtonElement.<anonymous> (ui_manager.js:118:10)
ui_manager.js:108 Uncaught TypeError: Cannot read properties of undefined (reading 'setAttribute')
    at HTMLButtonElement.<anonymous> (ui_manager.js:108:10)
ui_manager.js:113 Uncaught TypeError: Cannot read properties of undefined (reading 'setAttribute')
    at HTMLButtonElement.<anonymous> (ui_manager.js:113:10)
...
```

**Comment by zackees** [comment]
Yeah it's a bug. I JUST fixed it. I'm waiting for things to redeploy. The web compiler will see the fix in about 10 mins.

**Comment by hhrhhr** [comment]
> I JUST fixed it.

Is this what you mean (https://github.com/FastLED/FastLED/commit/0740901535b785e749291b5c8fcaad45c9cc566b)? Then you also need to fix the slider class:

https://github.com/FastLED/FastLED/blob/0c7a88d97c3737be961ae63b8a32612907e13310/src/platforms/wasm/compiler/modules/ui_manager.js#L62-L64

`this.value -> slider.value`, Otherwise, a similar error occurs:
```
ui_manager.js:63 Uncaught TypeError: Cannot read properties of undefined (reading 'value')
    at HTMLInputElement.<anonymous> (ui_manager.js:63:37)
(anonymous) @ ui_manager.js:63
```

**Comment by zackees** [comment]
> Is this what you mean ([FastLED/FastLED@0740901](https://github.com/FastLED/FastLED/commit/0740901535b785e749291b5c8fcaad45c9cc566b))? Then you also need to fix the slider class:


Weird, I wasn't getting an error with the slider. This all happened because the linter didn't like my use of functions so I replaced them with () => {} lambda and then "this" was no longer valid. Thanks for catching it!
